### ISSUE TITLE
Provide an example setup

### ISSUE THREAD

**Issue by thombergs** [silasmahler/eureka-prometheus-bridge#10]
Create a github repo that contains examples so that an interested user can easily run it to test the bridge. The repo should contain:
- [x] a Spring Boot App that acts as Eureka Server
- [x] two Spring Boot Apps that act as Eureka Clients
- [x] a guide on how to run the bridge to work with the eureka server 

- [x] Reminder: "/prometheus" endpoint needs to be defined by the eureka-clients.

Then:
 - [x] Link this repo from the README

**Comment by silasmahler** [comment]
Reminder: "/prometheus" endpoint needs to be defined by the eureka-clients.
