### ISSUE TITLE
Make Eureka query interval configurable

### ISSUE THREAD

**Issue by thombergs** [silasmahler/eureka-prometheus-bridge#11]
Currently, the interval to query Eureka is fix every 10 seconds, since it's defined in `@Scheduled(fixedRate = 10000)`

It would be nice to make this interval configurable. We could leave the `@Scheduled` annotation as is but add a check to the start that checks if the last job was longer than <configurable_interval> ago by storing the last execution time in an instance property (a little dirty, since the class has state then, but I wouldn't mind for this use case).

**Comment by silasmahler** [comment]
The most simple approach without destroying the scheduled job bean and restarting it seems to be following [this example ](https://stackoverflow.com/questions/15250928/how-to-change-springs-scheduled-fixeddelay-at-runtime) which is possible in spring boot. Also the default is most easy to implement like this. A separete Propertiesclass for one configuration would seem pretty unnesessary.
