### ISSUE TITLE
Dockerfile: use OpenJDK and MaxRam

### ISSUE THREAD

**Issue by kekru** [silasmahler/eureka-prometheus-bridge#23]
Hi Silas,
very interesting project!

I have a little enhancement for your Dockerfile:
 + Switch from `java` base image to `openjdk`, because `java` ist [deprecated](https://hub.docker.com/_/java/)
 + add the `-XX:MaxRAM` flag to avoid java taking more RAM than docker allows, which would lead to automatic shutdown of the container  

You'll find more information in my [Template for a Dockerfile to run a spring boot application](https://gist.github.com/kekru/e7414a9a689038b1153c48d9b2e30edf).  
You could also check out Halil's talk about [DBs and Java in Docker](https://jaxenter.de/datenbanken-docker-container-61507)

Best regards
Kevin

**Comment by silasmahler** [comment]
@kekru Thanks for the suggestion! Thats great to know, ill have a look into this tommorrow :)

**Comment by matti** [comment]
@kekru java can take more ram than `-XX:MaxRam` - for example `-Xmx` can be set higher and the total is larger than `-XX:MaxRam`

**Comment by kekru** [comment]
The RAM problem seems to be fixed at least in Java 8u191 and Java 10.  
See https://bugs.openjdk.java.net/browse/JDK-8146115#jbs-backportsPanel  
I tested it a few days ago with the openjdk:8u212-jre-slim-stretch image.
