### ISSUE TITLE
Use a YML library

### ISSUE THREAD

**Issue by thombergs** [silasmahler/eureka-prometheus-bridge#6]
Instead of handling the YML as a string, it should be handled with a YML library that allows handling it via Java (or Kotlin). This way, we have a refactoring-safe (and easier-to-test) way of dealing with YML.

**Comment by silasmahler** [comment]
https://github.com/KotlinBy/awesome-kotlin#libraries-frameworks-configuration

**Comment by silasmahler** [comment]
Trying to use this library https://github.com/daviddenton/configur8 to close the issue and also parts of #12

**Comment by silasmahler** [comment]
@thombergs What do you think of the yaml library? The EurekaProperties have been replaced with it in this [commit](https://github.com/adessoAG/eureka-prometheus-bridge/commit/0de33fd73c940df664756f89cf2079a126fbe67a). The PrometheusProperties will follow.
